CREATE view VIEW_Empleado_Listado

AS 
SELECT 
    EMPLE.ID_EMPLEADOS,
    (FAM.FAMILIA || ' - ' || FAM.CELULAR) PERSONASFAM,
    DNIEMPLEADO,
    NOMBREEMPLEADO,
	NOMBREESTABLECIMIENTO
	
    
FROM 
    EMPLEADOS EMPLE INNER JOIN PERSONASFAM FAM ON EMPLE.ID_PERSONASFAM=FAM.ID_PERSONASFAM
	inner join MAESTRO_ESTABLECIMIENTOS ESTA ON EMPLE.ID_ESTABLECIMIENTOS=ESTA.ID_ESTABLECIMIENTOS
    AND EMPLE.ESTADO='1';
    
    
    
    
 CREATE view VIEW_Empleado_Listado

AS 
SELECT 
    EMPLE.ID_EMPLEADOS,
    (FAM.NOMBRE || ' - ' || FAM.CELULAR) PERSONASFAM,
    DNIEMPLEADO,
    NOMBREEMPLEADO
	
	
    
FROM 
    EMPLEADOS EMPLE INNER JOIN PERSONASFAM FAM ON EMPLE.ID_EMPLEADOS=FAM.ID_EMPLEADOS
    AND EMPLE.ESTADO='1'; 
    

SELECT * FROM VIEW_Empleado_Listado